### ISSUE TITLE
[Docs] Add badges in README

### ISSUE THREAD

**Issue by alannt777** [alannt777/LicenseItCLI#21]
Every repo seems to have badges. I really don't understand how they work

Can someone help?

/cc @Aaron-Junker

**Comment by Aaron-Junker** [comment]
Https://Shields.io

**Comment by Aaron-Junker** [comment]
https://shields.io/

**Comment by alannt777** [comment]
Can you please give a PR?

**Comment by alannt777** [comment]
You know what? I will do it myself

**Comment by alannt777** [comment]
@Aaron-Junker You can review the PR though
